version: "3"
services:
  test-runner:
    image: maven:3-openjdk-18
    container_name: SDU-SE-F23-test
    volumes:
      - ./:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    command: bash -c "
      touch test.report &&
      rm test.report &&
      touch test.report &&
      mvn --batch-mode --update-snapshots verify -Dtestfx.robot=glass -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw >> test.report;"
