@startuml Player Movement
skinparam style strictuml
title Player Movement (UC01)

participant Core
participant Player
participant KeyboardController
participant KeyboardMovementController
participant MovingPart
participant SPILocator


activate Core
Core -> Player : start()
activate Player
Player -> SPILocator : locateAll(ControlSPI)
activate SPILocator
SPILocator -> Player : SPIs
deactivate SPILocator

Player -> KeyboardController : getType()
activate KeyboardController
KeyboardController -> Player : ControlType
deactivate KeyboardController

alt ControlType == KEYBOARD
Player -> KeyboardController : getMovementController()
activate KeyboardController
KeyboardController -> KeyboardMovementController : new()
activate KeyboardMovementController
KeyboardMovementController -> KeyboardController : KeyboardMovementController
deactivate KeyboardMovementController
KeyboardController -> Player : MovementController
deactivate KeyboardController

end alt

Player -> Core : void
deactivate Player

Core -> Player : process()
activate Player

Player -> MovingPart : process()
activate MovingPart

MovingPart -> KeyboardMovementController : getMovement()
activate KeyboardMovementController
KeyboardMovementController -> MovingPart : Direction
deactivate KeyboardMovementController

MovingPart -> Player : void
deactivate MovingPart

Player -> Core : void
deactivate Player
@enduml