@startuml

top to bottom direction
skinparam linetype ortho

class Asteroid {
  + Asteroid(): 
}
class AsteroidPlugin {
  + AsteroidPlugin(): 
  + start(GameData, World): void
  + stop(GameData, World): void
  - createAsteroid(GameData): Entity
}
class AsteroidProcessor {
  + AsteroidProcessor(): 
  - asteroidSplitter: IAsteroidSplitter
  + process(GameData, World): void
  + removeAsteroidSplitter(IAsteroidSplitter): void
  - setShape(Entity, int): void
   asteroidSplitter: IAsteroidSplitter
}
class AsteroidSplitterImpl {
  + AsteroidSplitterImpl(): 
  + createSplitAsteroid(Entity, World): void
}
class Bullet {
  + Bullet(): 
}
class BulletControlSystem {
  + BulletControlSystem(): 
  + process(GameData, World): void
  + createBullet(Entity, GameData): Entity
   shape: Entity
}
class BulletPlugin {
  + BulletPlugin(): 
  + stop(GameData, World): void
  + start(GameData, World): void
}
interface BulletSPI << interface >> {
  + createBullet(Entity, GameData): Entity
}
class CollisionDetector {
  + CollisionDetector(): 
  + process(GameData, World): void
  + collides(Entity, Entity): Boolean
}
class Enemy {
  + Enemy(): 
}
class EnemyControlSystem {
  + EnemyControlSystem(): 
  - updateShape(Entity): void
  + process(GameData, World): void
}
class EnemyPlugin {
  + EnemyPlugin(): 
  - createEnemyShip(GameData): Entity
  + start(GameData, World): void
  + stop(GameData, World): void
}
class Entity {
  + Entity(): 
  - shapeY: float[]
  - shapeX: float[]
  - ID: UUID
  - radius: float
  + getPart(Class): E
  + remove(Class): void
  + add(EntityPart): void
   shapeX: float[]
   radius: float
   shapeY: float[]
   ID: String
}
interface EntityPart << interface >> {
  + process(GameData, Entity): void
}
class Event {
  + Event(Entity): 
  - source: Entity
   source: Entity
}
class Game {
  + Game(): 
  - update(): void
  + pause(): void
  + create(): void
  + resize(int, int): void
  + resume(): void
  + render(): void
  - draw(): void
  + dispose(): void
   entityProcessingServices: Collection<IEntityProcessingService>
   pluginServices: Collection<IGamePluginService>
   postEntityProcessingServices: Collection<IPostEntityProcessingService>
}
class GameData {
  + GameData(): 
  - events: List<Event>
  - delta: float
  - keys: GameKeys
  - displayWidth: int
  - displayHeight: int
  + addEvent(Event): void
  + getEvents(Class<E>, String): List<Event>
  + removeEvent(Event): void
   displayHeight: int
   displayWidth: int
   keys: GameKeys
   delta: float
   events: List<Event>
}
class GameInputProcessor {
  + GameInputProcessor(GameData): 
  + keyDown(int): boolean
  + keyUp(int): boolean
}
class GameKeys {
  + GameKeys(): 
  + setKey(int, boolean): void
  + isDown(int): boolean
  + update(): void
  + isPressed(int): boolean
}
interface IAsteroidSplitter << interface >> {
  + createSplitAsteroid(Entity, World): void
}
interface IEntityProcessingService << interface >> {
  + process(GameData, World): void
}
interface IGamePluginService << interface >> {
  + start(GameData, World): void
  + stop(GameData, World): void
}
interface IPostEntityProcessingService << interface >> {
  + process(GameData, World): void
}
class LifePart {
  + LifePart(int): 
  - life: int
  - isHit: boolean
  - dead: boolean
  + setIsHit(boolean): void
  + process(GameData, Entity): void
   dead: boolean
   life: int
   isHit: boolean
}
class Main {
  + Main(): 
  + main(String[]): void
}
class MovingPart {
  + MovingPart(float, float, float, float): 
  - acceleration: float
  - right: boolean
  - rotationSpeed: float
  - dy: float
  - left: boolean
  - up: boolean
  - maxSpeed: float
  - deceleration: float
  - dx: float
  + process(GameData, Entity): void
   acceleration: float
   rotationSpeed: float
   up: boolean
   dy: float
   dx: float
   left: boolean
   maxSpeed: float
   deceleration: float
   speed: float
   right: boolean
}
class Player {
  + Player(): 
}
class PlayerControlSystem {
  + PlayerControlSystem(): 
  + process(GameData, World): void
  - updateShape(Entity): void
}
class PlayerPlugin {
  + PlayerPlugin(): 
  - createPlayerShip(GameData): Entity
  + stop(GameData, World): void
  + start(GameData, World): void
}
class PositionPart {
  + PositionPart(float, float, float): 
  - x: float
  - y: float
  - radians: float
  + process(GameData, Entity): void
  + setPosition(float, float): void
   radians: float
   x: float
   y: float
}
class SPILocator {
  - SPILocator(): 
  + locateAll(Class<T>): List<T>
}
class TimerPart {
  + TimerPart(float): 
  - expiration: float
  + process(GameData, Entity): void
  + reduceExpiration(float): void
   expiration: float
}
class World {
  + World(): 
  + getEntities(Class<E>[]): List<Entity>
  + removeEntity(String): void
  + getEntity(String): Entity
  + removeEntity(Entity): void
  + addEntity(Entity): String
   entities: Collection<Entity>
}

Asteroid                      -[#000082,plain]-^  Entity                       
AsteroidPlugin                -[#008200,dashed]-^  IGamePluginService           
AsteroidProcessor             -[#008200,dashed]-^  IEntityProcessingService     
AsteroidSplitterImpl          -[#008200,dashed]-^  IAsteroidSplitter            
Bullet                        -[#000082,plain]-^  Entity                       
BulletControlSystem           -[#008200,dashed]-^  BulletSPI                    
BulletControlSystem           -[#008200,dashed]-^  IEntityProcessingService     
BulletPlugin                  -[#008200,dashed]-^  IGamePluginService           
CollisionDetector             -[#008200,dashed]-^  IPostEntityProcessingService 
Enemy                         -[#000082,plain]-^  Entity                       
EnemyControlSystem            -[#008200,dashed]-^  IEntityProcessingService     
EnemyPlugin                   -[#008200,dashed]-^  IGamePluginService           
LifePart                      -[#008200,dashed]-^  EntityPart                   
MovingPart                    -[#008200,dashed]-^  EntityPart                   
Player                        -[#000082,plain]-^  Entity                       
PlayerControlSystem           -[#008200,dashed]-^  IEntityProcessingService     
PlayerPlugin                  -[#008200,dashed]-^  IGamePluginService           
PositionPart                  -[#008200,dashed]-^  EntityPart                   
TimerPart                     -[#008200,dashed]-^  EntityPart                   
@enduml
