@startuml Class diagram
'https://plantuml.com/class-diagram

abstract class Entity
abstract class GameState
interface IProcessingService
interface IPlugingService
interface IPostProcessingService
interface IEVentService
interface IEnemySpawner
class Core
class Game
class Enemy
class EnemySpawner
class Weapon
class Item
class Map
class DetectCollison
class Player
class Main
class LifePart
class Entity{
# Vector2 position
# Vector2 size
# Texture texture
+ {abstract} Texture loadImage()
+ {abstract} void render(SpriteBatch)
+ {abstract} void update()

}
interface IGamePlugingService{
 {abstract} + void start()
 {abstract} + void stop()
}

Entity <|-- Player
Entity <|-- Enemy
Entity <|-- Sword




@enduml